const actionTypes = {
  GET_USER_LIST: "GET_USER_LIST",
  GET_USER_LIST_REQUEST: "GET_USER_LIST_REQUEST",
  GET_USER_LIST_FAILURE: "GET_USER_LIST_FAILURE",
  GET_USER_POSTS_LIST: "GET_USER_POSTS_LIST",
  GET_USER_POSTS_LIST_REQUEST: "GET_USER_POSTS_LIST_REQUEST",
  GET_USER_POSTS_LIST_FAILURE: "GET_USER_POSTS_LIST_FAILURE",
  GET_USER_LIST_DETAIL: "GET_USER_LIST_DETAIL",
  GET_USER_LIST_DETAIL_REQUEST: "GET_USER_LIST_DETAIL_REQUEST",
  GET_USER_LIST_DETAIL_FAILURE: "GET_USER_LIST_DETAIL_FAILURE"
};

export default actionTypes;
