const actionTypes = {
  GET_USER_LIST: "GET_USER_LIST",
  GET_USER_LIST_REQUEST: "GET_USER_LIST_REQUEST",
  GET_USER_LIST_FAILURE: "GET_USER_LIST_FAILURE",
  GET_POSTS_LIST: "GET_POSTS_LIST",
  GET_POSTS_LIST_REQUEST: "GET_POSTS_LIST_REQUEST",
  GET_POSTS_LIST_FAILURE: "GET_POSTS_LIST_FAILURE",
  GET_ALBUM_PHOTOS_LIST: "GET_ALBUM_PHOTOS_LIST",
  GET_ALBUM_PHOTOS_LIST_REQUEST: "GET_ALBUM_PHOTOS_LIST_REQUEST",
  GET_ALBUM_PHOTOS_LIST_FAILURE: "GET_ALBUM_PHOTOS_LIST_FAILURE",
  GET_USER_POSTS_LIST: "GET_USER_POSTS_LIST",
  GET_USER_POSTS_LIST_REQUEST: "GET_USER_POSTS_LIST_REQUEST",
  GET_USER_POSTS_LIST_FAILURE: "GET_USER_POSTS_LIST_FAILURE",
  GET_DETAIL_COMMENTS_LIST: "GET_DETAIL_COMMENTS_LIST",
  GET_DETAIL_COMMENTS_LIST_REQUEST: "GET_DETAIL_COMMENTS_LIST_REQUEST",
  GET_DETAIL_COMMENTS_LIST_FAILURE: "GET_DETAIL_COMMENTS_LIST_FAILURE",
  GET_USER_ALBUMS_LIST: "GET_USER_ALBUMS_LIST",
  GET_USER_ALBUMS_LIST_REQUEST: "GET_USER_ALBUMS_LIST_REQUEST",
  GET_USER_ALBUMS_LIST_FAILURE: "GET_USER_ALBUMS_LIST_FAILURE",
  GET_USER_LIST_DETAIL: "GET_USER_LIST_DETAIL",
  GET_USER_LIST_DETAIL_REQUEST: "GET_USER_LIST_DETAIL_REQUEST",
  GET_USER_LIST_DETAIL_FAILURE: "GET_USER_LIST_DETAIL_FAILURE"
};

export default actionTypes;
